name: 编译
on: [ push, workflow_dispatch ]

jobs:
  dipper:
    permissions: { contents: write }
    uses: ./.github/workflows/build.yml
    with:
      ID: 1
      KERNEL_REPO: lineageOS/android_kernel_xiaomi_sdm845
      KERNEL_BRANCH: lineage-22.2
      AOSP_GCC: true
      DEVICE_NAME: dipper
      DEFCONFIG_NAME:
        vendor/xiaomi/mi845_defconfig
        vendor/xiaomi/dipper.config

  oppok9s:
    permissions: { contents: write }
    uses: ./.github/workflows/build.yml
    with:
      ID: 2
      KERNEL_REPO: fangkuaixiaoqiao/android_kernel_oppo_sm7325
      KERNEL_BRANCH: oppo/sm7325_u_14.0.0_k9s
      AOSP_GCC: true
      DEVICE_NAME: oppok9s
      DEFCONFIG_NAME:
        oppok9s_defconfig

  oppok9procn:
    permissions: { contents: write }
    uses: ./.github/workflows/build.yml
    with:
      ID: 3
      KERNEL_REPO: nishant6342/kernel_realme_RMX3031
      KERNEL_BRANCH: T
      AOSP_GCC: true
      DEVICE_NAME: oppok9procn
      DEFCONFIG_NAME:
        cupida_defconfig
